### PR TITLE
Socket connection added to vscodeclient.

### PR DESCRIPTION
**Pull request by Rodrigo-Barros**
Hi firstly I wanna say thanks for this great work for php community, phpactor ecosystem is awesome.

I wanna give my 2 cents, I made some additions to settings.json of vscode that allow the user:
-  launch and connect to language server via socket mode.
-  pass arguments to language server.

### CODE REVIEW

**Comment by dantleech** [comment]
Perfect, thanks :)

**Comment by dantleech** [comment]
Out of curiosity - what's the use case for using the socket connection?

**Comment by Rodrigo-Barros** [comment]
> Out of curiosity - what's the use case for using the socket connection?
Some specific scenarios like work on windows but developing for linux systems and WSL was not a option for me.

**Comment by dantleech** [comment]
I'm pleasantly surprised if it worked on native windows at all - keen to hear any feedback.

**Pull request merged**
