### PR TITLE
feat: Package Phpactor with composer

### PR DESCRIPTION
**Pull request by zobo**

### CODE REVIEW

**Comment by zobo** [comment]
Warning. This currently references an old version of phpactor so we can test Dependabot.

**Comment by dantleech** [comment]
hm, didn't we say we'd use the PHAR?

**Comment by zobo** [comment]
Initially yes, but I tried it with composer now - the same way I have it in vscode-php-intellisense.
The benefit is, we can use dependabot to automatically suggest updates to version when phpactor gets published. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

I'll try to find out what's the most agnostic way to download a file with a npm script - so that it will also work on windows (when we get there). 

But leave it open for now, I'm currently researching a strange behavior in phpactor, vsocde and positions character values.

**Comment by dantleech** [comment]
ok, it makes sense. One thing to be aware of is that it is not tested as a composer dependency, although I know people use it as such. It's probably fine, but wouldn't be entirely surprising if there were some path or other unexpected issues.

**Comment by zobo** [comment]
Do you want me to do any changes here or can we merge this and move on to other changes and dependabot configuration?

**Comment by dantleech** [comment]
my only reservation is that we are removing a feature (the ability to bump Phpactor to the latest version). But I doubt very few people (if any) use the bleeding edge of this package it's fine.

**Pull request merged**
